In [8]:
import numpy as np

In [13]:
A = np.array([[[1,1],[2,2]],[[3,3],[4,4]]])

In [14]:
A.shape

(2, 2, 2)

In [20]:
norms = (np.sum(A**2, axis=0))

In [21]:
norms

array([[10, 10],
       [20, 20]])

In [22]:
B = np.array([2,3,4,1])

In [23]:
x = np.array([1,3])

In [24]:
B[x]

array([3, 1])

In [30]:
import numpy as np

# 创建一个示例高维矩阵
matrix = np.random.random((3, 3, 3, 3))

# 使用 np.split 将高维矩阵分割成四个子矩阵
sub_matrices = np.split(matrix, [1, 2,3], axis=2)

# 打印分割后的四个子矩阵
print("Sub-matrix 1:")
print(sub_matrices[0])
print("\nSub-matrix 2:")
print(sub_matrices[1])
print("\nSub-matrix 3:")
print(sub_matrices[2])
print("\nSub-matrix 4:")
print(sub_matrices[3])

# 使用 np.concatenate 沿第三个维度合并第一个和第三个子矩阵
merged_matrix = np.concatenate([sub_matrices[0], sub_matrices[2]], axis=2)

# 打印合并后的矩阵
print("\nMerged Matrix:")
print(merged_matrix)


Sub-matrix 1:
[[[[0.35941    0.44755357 0.43383735]]

  [[0.61827055 0.9586577  0.68670911]]

  [[0.47275328 0.41597088 0.27264588]]]


 [[[0.55833589 0.05664012 0.05702946]]

  [[0.64079092 0.08800735 0.37111389]]

  [[0.7070047  0.72516714 0.84603494]]]


 [[[0.17061374 0.00409474 0.5039891 ]]

  [[0.22042426 0.48762619 0.84386812]]

  [[0.57898321 0.9643868  0.51701944]]]]

Sub-matrix 2:
[[[[0.52913079 0.58487936 0.43608955]]

  [[0.54411006 0.31299709 0.32709805]]

  [[0.70793431 0.24558969 0.86759297]]]


 [[[0.48011552 0.25196677 0.78021048]]

  [[0.18650389 0.45189715 0.83814359]]

  [[0.23820742 0.37131878 0.98801291]]]


 [[[0.34670259 0.90867968 0.56014886]]

  [[0.33402956 0.30052189 0.33999418]]

  [[0.69783072 0.83158529 0.31997419]]]]

Sub-matrix 3:
[[[[0.97995791 0.2663374  0.87009236]]

  [[0.22404068 0.88978874 0.66464092]]

  [[0.3485273  0.3356694  0.92137529]]]


 [[[0.86999295 0.62181188 0.07873569]]

  [[0.25208001 0.45529715 0.34263005]]

  [[0.26273658 0.8407983

In [33]:
# 使用 np.concatenate 沿第三个维度合并第一个和第三个子矩阵
merged_matrix2 = np.concatenate(sub_matrices[:1]+sub_matrices[2:], axis=2)

# 打印合并后的矩阵
print("\nMerged Matrix:")
print(merged_matrix2)


Merged Matrix:
[[[[0.35941    0.44755357 0.43383735]
   [0.97995791 0.2663374  0.87009236]]

  [[0.61827055 0.9586577  0.68670911]
   [0.22404068 0.88978874 0.66464092]]

  [[0.47275328 0.41597088 0.27264588]
   [0.3485273  0.3356694  0.92137529]]]


 [[[0.55833589 0.05664012 0.05702946]
   [0.86999295 0.62181188 0.07873569]]

  [[0.64079092 0.08800735 0.37111389]
   [0.25208001 0.45529715 0.34263005]]

  [[0.7070047  0.72516714 0.84603494]
   [0.26273658 0.84079839 0.1234802 ]]]


 [[[0.17061374 0.00409474 0.5039891 ]
   [0.54612209 0.12360062 0.58120056]]

  [[0.22042426 0.48762619 0.84386812]
   [0.03315382 0.58762525 0.03246596]]

  [[0.57898321 0.9643868  0.51701944]
   [0.22831944 0.84325339 0.85382828]]]]
